# -*- coding: utf-8 -*-
"""ArcMap_Selekcja_Z_Wnioskami.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ob5T_D_tEoc-BTNl9zmG9sMwBQ6l9wtJ
"""

# -*- coding: utf-8 -*-
import arcpy

#napisuje wyniki przekształceń \/
arcpy.env.overwriteOutput = True

def selekcja():
    try:

        nazwa_warstwy = arcpy.GetParameterAsText(0)
        miejsce_zapisu = arcpy.GetParameterAsText(1)
        #ciało funkcji

        #przypisanie ciągu znaków z parametrów do nazwa



        #komunikat
        arcpy.AddMessage(" Początek pracy narzędzia ")
        # zrobione przeze mnie
        '''where_clause = """{} = {}""".format(arcpy.AddFieldDelimiters(nazwa_warstwy,Field),Feature)
        arcpy.AddMessage(where_clause)

        arcpy.SelectLayerByAttribute_management(nazwa_warstwy,"NEW_SELECTION",where_clause) '''

        #bartek

        nazwa_wioski = arcpy.GetParameterAsText(2)
        zapytanie_sql = ' \"NAZWA\" = \'' + str(nazwa_wioski) + '\' '
        arcpy.SelectLayerByAttribute_management(nazwa_warstwy, "NEW_SELECTION", zapytanie_sql)


        arcpy.CopyFeatures_management(nazwa_warstwy, miejsce_zapisu)
        #arcpy.SelectLayerByAttribute_management(nazwa_warstwy, "NEW_SELECTION",' \"NAZWA\" = \'Babiak\' ')




        arcpy.SelectLayerByAttribute_management(nazwa_warstwy, "CLEAR_SELECTION")
        arcpy.AddMessage(" Koniec pracy narzędzia ")

    #obsługa wyjątków
    except Exception, err:
        arcpy.AddError("blad nazwa_narzędzia")
        arcpy.AddError(sys.exc_traceback.tb_lineno)
        arcpy.AddError(err.message)
    #dekcje końcowe
    finally:
            pass

if __name__ == '__main__':
    selekcja()