# -*- coding: utf-8 -*-
"""ArcMap_ArkuszePowiatow.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmEuXyACfEpJc7xl96otf6COOkuEX42f
"""

# -*- coding: utf-8 -*-
import arcpy
#rozbudowa funkcjinalnosci arcgis w przetwarzaniu danych przestrzennych

#napisuje wyniki przekształceń \/
arcpy.env.overwriteOutput = True

def wycinanie():
    try:

        dane_wejsciowe=arcpy.GetParameterAsText(0)
        warstwa_wycinajaca=arcpy.GetParameterAsText(1)
        miejsce_zapisu=arcpy.GetParameterAsText(2)
        przedrostek=arcpy.GetParameterAsText(3)
        nazwa_wiochy = arcpy.GetParameterAsText(4)

        lista=dane_wejsciowe.split(';')
        arcpy.AddMessage(str(lista))
        arcpy.AddMessage( " " )
        arcpy.AddMessage(dane_wejsciowe)
        arcpy.AddMessage(warstwa_wycinajaca)
        arcpy.AddMessage(miejsce_zapisu)
        arcpy.AddMessage(przedrostek)


        zapytanie_sql = ' \"jpt_kod_je\" = \'' + str(nazwa_wiochy) + '\' '
        arcpy.SelectLayerByAttribute_management(warstwa_wycinajaca, "NEW_SELECTION",zapytanie_sql)


        for dane in lista:
            arcpy.AddMessage(dane)
            #arcpy.Clip_analysis(dane,warstwa_wycinajaca,miejsce_zapisu+'\\'+str(przedrostek)+dane)
            arcpy.Clip_analysis(dane,warstwa_wycinajaca,miejsce_zapisu)
        arcpy.SelectLayerByAttribute_management(warstwa_wycinajaca, "CLEAR_SELECTION")


        #obliczenie pow calego wojewodztwa
        arcpy.AddField_management(miejsce_zapisu, 'Shape_Area', 'DOUBLE')
        arcpy.CalculateField_management(miejsce_zapisu, 'Shape_Area', '!shape.area!', 'PYTHON')




        #ile procent arkusza zajmuje dany powiat
        expression = "getClass(round((!SHAPE.area!/20750000)*100))"
        codeblock = """def getClass(area):
            if area > 100:
                return area-1
            else:
                return area"""
        #arcpy.AddField_management(miejsce_zapisu, 'Proc_Arkus', 'DOUBLE')
        #arcpy.CalculateField_management(miejsce_zapisu, 'Proc_Arkus', 'round((!Shape_Area!/20750000)*100)', 'PYTHON')
        arcpy.AddField_management(miejsce_zapisu, 'Proc_Arkus', 'DOUBLE')
        arcpy.CalculateField_management(miejsce_zapisu, 'Proc_Arkus', expression, 'PYTHON_9.3',codeblock)





    #obsługa wyjątków
    except Exception, err:
        arcpy.AddError("blad wycinanie")
        arcpy.AddError(sys.exc_traceback.tb_lineno)
        arcpy.AddError(err.message)
    #dekcje końcowe
    finally:
            pass

if __name__ == '__main__':
    wycinanie()