# -*- coding: utf-8 -*-
"""ArcMap_Wybieranie_do_Shape.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SQg5vqr6hshFi-mEDz1iU4F0sWgacSdz
"""

# -*- coding: utf-8 -*-
import arcpy
import os
#napisuje wyniki przekształceń \/
arcpy.env.overwriteOutput = True

def wybieranie():
    try:
        plik_txt=arcpy.GetParameterAsText(0)   #dodanie parametru do narzedia w arcmapie
        plik=open(plik_txt)
        lista=[]
        for rekord in plik.readlines():
            linia=rekord.rstrip()        # usuwa biale znaki z prawej strony
            wartosci=linia.split(";")     #do listy dodaje wartosci oddzielone ;
            lista.append(wartosci)
        wyjscie=arcpy.GetParameterAsText(1)
        #utworzenie pliku shp
        arcpy.CreateFeatureclass_management(os.path.dirname(wyjscie), os.path.basename(wyjscie), "POINT") #point - typ geometrii
        arcpy.AddField_management(wyjscie, "id_prng", "TEXT", 30)
        arcpy.AddField_management(wyjscie, "naz_glowna", "TEXT", 30)
        arcpy.AddField_management(wyjscie, "rodzaj_obi", "TEXT", 30)
        cur = arcpy.da.InsertCursor(wyjscie, ["SHAPE@","id_prng","naz_glowna","rodzaj_obi"])
        #utworzenie pliku na zapis wspolrzednych punktow
        zapis_txt=arcpy.GetParameterAsText(2)
        zapis=open(zapis_txt,"w")
        sciezka = arcpy.GetParameterAsText(3)
        #utworzenie listy wyboru parametru do tworzenia pliku shp o wybranej zawartosci
        rodzaj_obiektu=arcpy.GetParameterAsText(4)
        if rodzaj_obiektu=='1':
            rodzaj_obiektu = 'czesc miasta.shp'
        elif rodzaj_obiektu=='2':
            rodzaj_obiektu = 'czesc wsi.shp'
        elif rodzaj_obiektu =='3':
            rodzaj_obiektu = 'miasto.shp'
        elif rodzaj_obiektu =='4':
            rodzaj_obiektu='przysiolek wsi.shp'
        else:
            rodzaj_obiektu = 'wies.shp'
        arcpy.CreateFeatureclass_management(sciezka, (rodzaj_obiektu), "POINT")
        arcpy.AddField_management(sciezka+'\\'+rodzaj_obiektu, "rodzaj_obi", "TEXT", 30)
        cur1=arcpy.da.InsertCursor(sciezka+'\\'+rodzaj_obiektu,["SHAPE@","rodzaj_obi"])
        #ustalenie co bedzie zapisywane w pliku głównym shp oraz w pliku tekstowym
        i=0
        for dane in lista:
            if i == 0:
                i =+ 1
            else:
                x = round(float(dane[-2].replace(",",".") ),1)
                y = round(float(dane[-1].replace(",",".") ),1)
                cur.insertRow([arcpy.Point( x , y ),dane[1],dane[2],dane[3]])
                zapis.writelines(str(x)+' '+str(y)+"\n")
        #czesc ktora bedzie tworzyla pliki shp przez wybrany parametr
        for dane in lista:
            if rodzaj_obiektu=='miasto.shp':
                if dane[3] == 'miasto':
                    x = round(float(dane[-2].replace(",",".") ),3)
                    y = round(float(dane[-1].replace(",",".") ),3)
                    cur1.insertRow([arcpy.Point( x , y ),dane[3]])
            if rodzaj_obiektu == 'wies.shp':
                if len(dane[3])==5:   #zapytac dlaczego dla if dane[3] =='wies' nie dziala, skoro wyzej dla zapis.writelines UTF-8 dziala i normalnie zapisuje polskie znaki do tabeli jak i pliku, gdy zmienie wieś na wies to dziala normalnie i wczytuje bez problemu
                    x = round(float(dane[-2].replace(",",".") ),3)
                    y = round(float(dane[-1].replace(",",".") ),3)
                    cur1.insertRow([arcpy.Point( x , y ),dane[3]])
            if rodzaj_obiektu == 'czesc wsi.shp':
                if len(dane[3])==12:
                        x = round(float(dane[-2].replace(",", ".")), 3)
                        y = round(float(dane[-1].replace(",", ".")), 3)
                        cur1.insertRow([arcpy.Point(x, y), dane[3]])
            if rodzaj_obiektu == 'czesc miasta.shp':
                if len(dane[3])==15:
                        x = round(float(dane[-2].replace(",", ".")), 3)
                        y = round(float(dane[-1].replace(",", ".")), 3)
                        cur1.insertRow([arcpy.Point(x, y), dane[3]])
            if rodzaj_obiektu == 'przysiolek wsi.shp':
                if len(dane[3])==16:
                        x = round(float(dane[-2].replace(",", ".")), 3)
                        y = round(float(dane[-1].replace(",", ".")), 3)
                        cur1.insertRow([arcpy.Point(x, y), dane[3]])
        #wypisanie najdluzszego ciagu znakowego z pliku
        s=0
        for dlug in lista:
            if len(dlug[2])>s:
                s=len(dlug[2])
        arcpy.AddWarning('Najdluzszy ciag znakowy w pliku')
        arcpy.AddMessage(s)
    #obsługa wyjątków
    except Exception, err:
        arcpy.AddError("blad nazwa_narzędzia")
        arcpy.AddError(sys.exc_traceback.tb_lineno)
        arcpy.AddError(err.message)
    #dekcje końcowe
    finally:
            pass

if __name__ == '__main__':
    kolos()